### ISSUE TITLE
Rendering Engine

### ISSUE THREAD

**Issue by Thraka** [TheGrandUser/DragonRising#1]
Hi!

I was just browsing people doing ascii type stuff and found your project. 

Originally I started down the WPF path also but I just found it too weird to try and replicate a console experience. And then when I wanted to do other things like multiple consoles, resized consoles, using other fonts and the like. Then I looked at just doing simple 2d sprite-based stuff in XNA and my game engine was born. Right now it compiles to MonoGame for portability. I even had it compiling to Silverlight at one point and it should still be able to.

I've been working on an ascii-style game engine for other .NET programmers to use for about 5-years now and it's available at https://github.com/Thraka/SadConsole. I really am looking for people to start using it to make games. Your game looks like a serious possibility and I would love to know if you would like to try it out.

You should be able to just compile the entire engine no problem. There is a StarterProject folder that makes an EXE that demonstrates some of the engine features. 

Let me know what you think! 

Cheers!

**Comment by TheGrandUser** [comment]
I could take a look at it later, though I'm currently happy with my WPF terminal control. How were you trying to use WPF before? Were you trying to use text blocks or similar, or did you get into the lower level drawing context (which is what I'm doing here)?

**Comment by Thraka** [comment]
Yeah originally I was doing the textblock thing. I think I started to look at the lower level stuff but then I figured why not just use an actual game engine to render it, as it would be portable to other platforms, and went down that route :)

Since I'm using a 2d sprite engine to render console stuff you get a lot more advantages too, such as being able to redefine the character set graphics among other special effects. I've also been working on (it's on github too) an editor project that lets you draw out consoles and screens. I'm almost done implemented animation in the editor, though the engine supports it fully.

**Comment by Thraka** [comment]
Ok so I was doing some twitch streaming while working on the screen editor tool for the ASCII engine. I created a highlight video showing the starter project so you can just watch the two minute video and see some quick features. http://www.twitch.tv/thrakaandy/c/5860455 

I looked through your code, game looks nice :) 

You use some interfaces for rendering, but then in your main game you don't use the interface as the object reference, you use an actual type that implements the interface. I was looking at the possibility of making a renderer for your game that used my engine so you didn't have to do any work and I would have something to test with.

I don't have the exact file but I'll find the reference and open another issue. (I'm on a different computer)

**Comment by TheGrandUser** [comment]
If you're referring to the DragonRising project as the main game, (as opposed to the DragonRising.Game) that's by intent. IT would have been more accurate to name that one DragonRising.Wpf, with the idea that it would have the concrete things for rendering and data storage (which is what I'm working on at the moment). Feel free to fork my project and add a DraconicEngine.SadConsole and/or a DragonRising.SadConsole to test with
